# Generated by Django 5.2.5 on 2025-09-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_etario', models.CharField(max_length=50)),
                ('imagen_nombre', models.CharField(default='default.png', max_length=100)),
            ],
        ),
    ]
