# Generated by Django 5.2.5 on 2025-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vacunas/'),
        ),
    ]
