# Generated by Django 5.2.5 on 2025-09-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0002_vacuna_descripcion_corta_vacuna_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermedad',
            options={'verbose_name': 'Enfermedad', 'verbose_name_plural': 'Enfermedades'},
        ),
        migrations.AlterModelOptions(
            name='grupoetario',
            options={'verbose_name': 'Grupo Etario', 'verbose_name_plural': 'Grupos Etarios'},
        ),
        migrations.AlterField(
            model_name='grupoetario',
            name='edad_max',
            field=models.IntegerField(help_text='Edad máxima en meses'),
        ),
        migrations.AlterField(
            model_name='grupoetario',
            name='edad_min',
            field=models.IntegerField(help_text='Edad mínima en meses'),
        ),
    ]
